FROM base_image:latest

COPY ../models/ .

COPY ../inference.py .

COPY main.py .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

# docker build -t backend:v1 -f Dockerfile.backend .
# docker run -d -p 5000:8000 --name backend-pod backend:v1

