# docker-compose -f docker-compose.yml up --build
# docker-compose -f docker-compose.yml down

version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  producer-1:
    build:
      context: .
      dockerfile: Dockerfile.producer
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer-add_product:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      - TOPIC=add_product
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy
    

  consumer-availability:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      - TOPIC=availability
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy
  consumer-request_refund:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      - TOPIC=request_refund
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_cache
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API (faster for bulk)
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always
