FROM base_image:latest

WORKDIR /app 

COPY producer_class.py .
COPY producer.py .
COPY inference.py .
COPY ./models .
COPY logger_config.py .
COPY prioritize_strategy.py .

CMD ["python", "-u", "producer.py"]