
# docker-compose -f docker-compose-backend.yml up --build
# docker-compose -f docker-compose-backend.yml down


version: '3.8'

services:
  # 1. RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"   
      - "15672:15672" 
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Qdrant Service
  qdrant:
    build:
      context: .
      dockerfile: Dockerfile.qdrant
    container_name: qdrant-container
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  # 3. Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-container
    ports:
      - "5000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      qdrant:
        condition: service_started
    environment:
      - QDRANT_HOST=qdrant
      - RABBITMQ_HOST=rabbitmq
      - PRIORITY_STRATEGY=intent

  consumer-add_product:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      - TOPIC=add_product
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy
  

  consumer-availability:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      - TOPIC=availability
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy
  consumer-request_refund:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      - TOPIC=request_refund
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  qdrant_storage: