FROM intent-classifier-api:latest

# 1. Install pika (for RabbitMQ) and spacy
RUN pip install --no-cache-dir pika spacy

# 2. Download the English language model (crucial for LemmatizeHandler)
RUN python -m spacy download en_core_web_sm

COPY producer.py .
# COPY intent_classifier_v1.joblib . # Only if not in base

CMD ["python", "producer.py"]